USE `cligrep`;

ALTER TABLE cli_registry
  ADD COLUMN IF NOT EXISTS FAVORITE_COUNT_ INT NOT NULL DEFAULT 0 AFTER EXECUTABLE_,
  ADD COLUMN IF NOT EXISTS COMMENT_COUNT_ INT NOT NULL DEFAULT 0 AFTER FAVORITE_COUNT_,
  ADD COLUMN IF NOT EXISTS RUN_COUNT_ INT NOT NULL DEFAULT 0 AFTER COMMENT_COUNT_;

UPDATE cli_registry c
LEFT JOIN (
  SELECT CLI_SLUG_, COUNT(*) AS FAVORITE_COUNT_
  FROM user_favorite
  GROUP BY CLI_SLUG_
) f ON f.CLI_SLUG_ = c.SLUG_
SET c.FAVORITE_COUNT_ = COALESCE(f.FAVORITE_COUNT_, 0);

UPDATE cli_registry c
LEFT JOIN (
  SELECT CLI_SLUG_, COUNT(*) AS COMMENT_COUNT_
  FROM user_comment
  GROUP BY CLI_SLUG_
) m ON m.CLI_SLUG_ = c.SLUG_
SET c.COMMENT_COUNT_ = COALESCE(m.COMMENT_COUNT_, 0);

UPDATE cli_registry c
LEFT JOIN (
  SELECT CLI_SLUG_, COUNT(*) AS RUN_COUNT_
  FROM sandbox_execution_log
  GROUP BY CLI_SLUG_
) e ON e.CLI_SLUG_ = c.SLUG_
SET c.RUN_COUNT_ = COALESCE(e.RUN_COUNT_, 0);

DROP TABLE IF EXISTS seed_execution_record;
