USE `cligrep`;

ALTER TABLE cli_registry
  ADD COLUMN IF NOT EXISTS UPDATED_AT_ DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) AFTER CREATED_AT_,
  ADD COLUMN IF NOT EXISTS PUBLISHED_AT_ DATETIME(3) NULL AFTER UPDATED_AT_,
  ADD COLUMN IF NOT EXISTS OWNER_USER_ID_ BIGINT UNSIGNED NULL AFTER RUN_COUNT_,
  ADD COLUMN IF NOT EXISTS STATUS_ VARCHAR(32) NOT NULL DEFAULT 'published' AFTER OWNER_USER_ID_,
  ADD COLUMN IF NOT EXISTS EXECUTION_TEMPLATE_ VARCHAR(64) NOT NULL DEFAULT '' AFTER STATUS_;

ALTER TABLE cli_registry
  ADD INDEX IF NOT EXISTS IDX_CLI_REGISTRY_OWNER_STATUS (OWNER_USER_ID_, STATUS_);

UPDATE cli_registry
SET UPDATED_AT_ = COALESCE(UPDATED_AT_, CREATED_AT_),
    STATUS_ = CASE
      WHEN OWNER_USER_ID_ IS NULL THEN 'published'
      WHEN STATUS_ NOT IN ('draft', 'published') THEN 'draft'
      ELSE STATUS_
    END,
    PUBLISHED_AT_ = CASE
      WHEN OWNER_USER_ID_ IS NULL AND PUBLISHED_AT_ IS NULL THEN CREATED_AT_
      WHEN STATUS_ = 'published' AND PUBLISHED_AT_ IS NULL THEN UPDATED_AT_
      ELSE PUBLISHED_AT_
    END;

CREATE TABLE IF NOT EXISTS auth_role (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ROLE_KEY_ VARCHAR(64) NOT NULL,
  DISPLAY_NAME_ VARCHAR(255) NOT NULL DEFAULT '',
  CREATED_AT_ DATETIME(3) NOT NULL,
  UPDATED_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (ID_),
  UNIQUE KEY UK_AUTH_ROLE_KEY (ROLE_KEY_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_user_role (
  USER_ID_ BIGINT UNSIGNED NOT NULL,
  ROLE_ID_ BIGINT UNSIGNED NOT NULL,
  CREATED_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (USER_ID_, ROLE_ID_),
  KEY IDX_AUTH_USER_ROLE_ROLE_USER (ROLE_ID_, USER_ID_),
  CONSTRAINT FK_AUTH_USER_ROLE_USER FOREIGN KEY (USER_ID_) REFERENCES auth_user (ID_) ON DELETE CASCADE,
  CONSTRAINT FK_AUTH_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID_) REFERENCES auth_role (ID_) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO auth_role (ROLE_KEY_, DISPLAY_NAME_, CREATED_AT_, UPDATED_AT_)
VALUES
  ('member', 'Member', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
  ('platform_admin', 'Platform Admin', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3))
ON DUPLICATE KEY UPDATE
  DISPLAY_NAME_ = VALUES(DISPLAY_NAME_),
  UPDATED_AT_ = VALUES(UPDATED_AT_);

ALTER TABLE cli_release_asset
  ADD COLUMN IF NOT EXISTS STORAGE_KIND_ VARCHAR(64) NOT NULL DEFAULT '' AFTER SIZE_BYTES_,
  ADD COLUMN IF NOT EXISTS STORAGE_PATH_ VARCHAR(1024) NOT NULL DEFAULT '' AFTER STORAGE_KIND_;
