USE `cligrep`;

CREATE TABLE IF NOT EXISTS admin_api_key (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME_ VARCHAR(255) NOT NULL,
  KEY_PREFIX_ VARCHAR(64) NOT NULL,
  KEY_HASH_ CHAR(64) NOT NULL,
  CREATED_BY_USER_ID_ BIGINT UNSIGNED NOT NULL,
  CREATED_AT_ DATETIME(3) NOT NULL,
  LAST_USED_AT_ DATETIME(3) NULL,
  REVOKED_AT_ DATETIME(3) NULL,
  PRIMARY KEY (ID_),
  UNIQUE KEY UK_ADMIN_API_KEY_HASH (KEY_HASH_),
  KEY IDX_ADMIN_API_KEY_CREATED_BY (CREATED_BY_USER_ID_, CREATED_AT_),
  KEY IDX_ADMIN_API_KEY_ACTIVE (REVOKED_AT_, CREATED_AT_),
  CONSTRAINT FK_ADMIN_API_KEY_CREATED_BY FOREIGN KEY (CREATED_BY_USER_ID_) REFERENCES auth_user (ID_) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
