USE `cligrep`;

CREATE TABLE IF NOT EXISTS cli_registry (
  SLUG_ VARCHAR(128) NOT NULL,
  DISPLAY_NAME_ VARCHAR(255) NOT NULL,
  SUMMARY_ TEXT NOT NULL,
  TYPE_ VARCHAR(64) NOT NULL,
  TAGS_JSON_ JSON NOT NULL,
  HELP_TEXT_ MEDIUMTEXT NOT NULL,
  VERSION_TEXT_ VARCHAR(255) NOT NULL,
  POPULARITY_ INT NOT NULL,
  RUNTIME_IMAGE_ VARCHAR(255) NOT NULL,
  ENABLED_ TINYINT(1) NOT NULL DEFAULT 1,
  EXAMPLE_LINE_ VARCHAR(512) NOT NULL,
  ENVIRONMENT_KIND_ VARCHAR(32) NOT NULL,
  SOURCE_TYPE_ VARCHAR(64) NOT NULL,
  AUTHOR_ VARCHAR(255) NOT NULL DEFAULT '',
  GITHUB_URL_ VARCHAR(512) NOT NULL DEFAULT '',
  GITEE_URL_ VARCHAR(512) NOT NULL DEFAULT '',
  LICENSE_ VARCHAR(128) NOT NULL DEFAULT '',
  CREATED_AT_ DATETIME(3) NOT NULL,
  ORIGINAL_COMMAND_ VARCHAR(512) NOT NULL DEFAULT '',
  EXECUTABLE_ TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (SLUG_),
  KEY IDX_CLI_REGISTRY_ENABLED_ENV_TYPE (ENABLED_, ENVIRONMENT_KIND_, TYPE_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_user (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USERNAME_ VARCHAR(128) NOT NULL,
  DISPLAY_NAME_ VARCHAR(255) NOT NULL DEFAULT '',
  EMAIL_ VARCHAR(255) NOT NULL DEFAULT '',
  AVATAR_URL_ VARCHAR(1024) NOT NULL DEFAULT '',
  AUTH_PROVIDER_ VARCHAR(32) NOT NULL DEFAULT 'mock',
  AUTH_SUB_ VARCHAR(255) NULL,
  IP_ VARCHAR(64) NOT NULL,
  CREATED_AT_ DATETIME(3) NOT NULL,
  UPDATED_AT_ DATETIME(3) NOT NULL,
  LAST_LOGIN_AT_ DATETIME(3) NULL,
  PRIMARY KEY (ID_),
  UNIQUE KEY UK_AUTH_USER_USERNAME (USERNAME_),
  UNIQUE KEY UK_AUTH_USER_PROVIDER_SUB (AUTH_PROVIDER_, AUTH_SUB_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_local_credential (
  USER_ID_ BIGINT UNSIGNED NOT NULL,
  PASSWORD_HASH_ VARCHAR(255) NOT NULL,
  PASSWORD_UPDATED_AT_ DATETIME(3) NOT NULL,
  CREATED_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (USER_ID_),
  CONSTRAINT FK_AUTH_LOCAL_CREDENTIAL_USER FOREIGN KEY (USER_ID_) REFERENCES auth_user (ID_) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_session (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID_ BIGINT UNSIGNED NOT NULL,
  TOKEN_HASH_ CHAR(64) NOT NULL,
  EXPIRES_AT_ DATETIME(3) NOT NULL,
  CREATED_AT_ DATETIME(3) NOT NULL,
  LAST_SEEN_AT_ DATETIME(3) NOT NULL,
  USER_AGENT_ VARCHAR(512) NOT NULL DEFAULT '',
  IP_ VARCHAR(64) NOT NULL DEFAULT '',
  PRIMARY KEY (ID_),
  UNIQUE KEY UK_AUTH_SESSION_TOKEN_HASH (TOKEN_HASH_),
  KEY IDX_AUTH_SESSION_USER_EXPIRES (USER_ID_, EXPIRES_AT_),
  CONSTRAINT FK_AUTH_SESSION_USER FOREIGN KEY (USER_ID_) REFERENCES auth_user (ID_) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_login_log (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID_ BIGINT UNSIGNED NULL,
  USERNAME_ VARCHAR(128) NOT NULL DEFAULT '',
  DISPLAY_NAME_ VARCHAR(255) NOT NULL DEFAULT '',
  AUTH_METHOD_ VARCHAR(32) NOT NULL,
  LOGIN_RESULT_ VARCHAR(16) NOT NULL,
  FAILURE_REASON_ VARCHAR(128) NOT NULL DEFAULT '',
  IP_ VARCHAR(64) NOT NULL DEFAULT '',
  USER_AGENT_ VARCHAR(512) NOT NULL DEFAULT '',
  LOGIN_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (ID_),
  KEY IDX_AUTH_LOGIN_LOG_USER_AT (USER_ID_, LOGIN_AT_),
  KEY IDX_AUTH_LOGIN_LOG_METHOD_AT (AUTH_METHOD_, LOGIN_AT_),
  CONSTRAINT FK_AUTH_LOGIN_LOG_USER FOREIGN KEY (USER_ID_) REFERENCES auth_user (ID_) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_favorite (
  USER_ID_ BIGINT UNSIGNED NOT NULL,
  CLI_SLUG_ VARCHAR(128) NOT NULL,
  CREATED_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (USER_ID_, CLI_SLUG_),
  KEY IDX_USER_FAVORITE_USER_CREATED (USER_ID_, CREATED_AT_),
  CONSTRAINT FK_USER_FAVORITE_USER FOREIGN KEY (USER_ID_) REFERENCES auth_user (ID_) ON DELETE CASCADE,
  CONSTRAINT FK_USER_FAVORITE_CLI FOREIGN KEY (CLI_SLUG_) REFERENCES cli_registry (SLUG_) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_comment (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CLI_SLUG_ VARCHAR(128) NOT NULL,
  USER_ID_ BIGINT UNSIGNED NOT NULL,
  BODY_ TEXT NOT NULL,
  CREATED_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (ID_),
  KEY IDX_USER_COMMENT_CLI_CREATED (CLI_SLUG_, CREATED_AT_),
  KEY IDX_USER_COMMENT_USER_CREATED (USER_ID_, CREATED_AT_),
  CONSTRAINT FK_USER_COMMENT_USER FOREIGN KEY (USER_ID_) REFERENCES auth_user (ID_) ON DELETE CASCADE,
  CONSTRAINT FK_USER_COMMENT_CLI FOREIGN KEY (CLI_SLUG_) REFERENCES cli_registry (SLUG_) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sandbox_execution_log (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID_ BIGINT UNSIGNED NULL,
  CLI_SLUG_ VARCHAR(128) NOT NULL,
  LINE_ TEXT NOT NULL,
  MODE_ VARCHAR(64) NOT NULL,
  STDOUT_ MEDIUMTEXT NOT NULL,
  STDERR_ MEDIUMTEXT NOT NULL,
  EXIT_CODE_ INT NOT NULL,
  DURATION_MS_ BIGINT NOT NULL,
  CREATED_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (ID_),
  KEY IDX_SANDBOX_EXECUTION_LOG_CLI_CREATED (CLI_SLUG_, CREATED_AT_),
  CONSTRAINT FK_SANDBOX_EXECUTION_LOG_USER FOREIGN KEY (USER_ID_) REFERENCES auth_user (ID_) ON DELETE SET NULL,
  CONSTRAINT FK_SANDBOX_EXECUTION_LOG_CLI FOREIGN KEY (CLI_SLUG_) REFERENCES cli_registry (SLUG_) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sandbox_generated_asset (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  KIND_ VARCHAR(64) NOT NULL,
  NAME_ VARCHAR(255) NOT NULL,
  CLI_SLUG_ VARCHAR(128) NULL,
  USER_ID_ BIGINT UNSIGNED NULL,
  CONTENT_ MEDIUMTEXT NOT NULL,
  CREATED_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (ID_),
  KEY IDX_SANDBOX_GENERATED_ASSET_KIND_CREATED (KIND_, CREATED_AT_),
  CONSTRAINT FK_SANDBOX_GENERATED_ASSET_USER FOREIGN KEY (USER_ID_) REFERENCES auth_user (ID_) ON DELETE SET NULL,
  CONSTRAINT FK_SANDBOX_GENERATED_ASSET_CLI FOREIGN KEY (CLI_SLUG_) REFERENCES cli_registry (SLUG_) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS seed_execution_record (
  SEED_KEY_ VARCHAR(128) NOT NULL,
  CLI_SLUG_ VARCHAR(128) NOT NULL,
  CREATED_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (SEED_KEY_),
  CONSTRAINT FK_SEED_EXECUTION_RECORD_CLI FOREIGN KEY (CLI_SLUG_) REFERENCES cli_registry (SLUG_) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cli_release (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CLI_SLUG_ VARCHAR(128) NOT NULL,
  VERSION_ VARCHAR(128) NOT NULL,
  PUBLISHED_AT_ DATETIME(3) NOT NULL,
  IS_CURRENT_ TINYINT(1) NOT NULL DEFAULT 0,
  SOURCE_KIND_ VARCHAR(64) NOT NULL DEFAULT '',
  SOURCE_URL_ VARCHAR(1024) NOT NULL DEFAULT '',
  CREATED_AT_ DATETIME(3) NOT NULL,
  UPDATED_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (ID_),
  UNIQUE KEY UK_CLI_RELEASE_SLUG_VERSION (CLI_SLUG_, VERSION_),
  KEY IDX_CLI_RELEASE_SLUG_PUBLISHED (CLI_SLUG_, PUBLISHED_AT_),
  KEY IDX_CLI_RELEASE_SLUG_CURRENT (CLI_SLUG_, IS_CURRENT_),
  CONSTRAINT FK_CLI_RELEASE_CLI FOREIGN KEY (CLI_SLUG_) REFERENCES cli_registry (SLUG_) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cli_release_asset (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  RELEASE_ID_ BIGINT UNSIGNED NOT NULL,
  FILE_NAME_ VARCHAR(255) NOT NULL,
  DOWNLOAD_URL_ VARCHAR(1024) NOT NULL,
  OS_ VARCHAR(64) NOT NULL DEFAULT '',
  ARCH_ VARCHAR(64) NOT NULL DEFAULT '',
  PACKAGE_KIND_ VARCHAR(64) NOT NULL DEFAULT '',
  CHECKSUM_URL_ VARCHAR(1024) NOT NULL DEFAULT '',
  SIZE_BYTES_ BIGINT NOT NULL DEFAULT 0,
  CREATED_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (ID_),
  KEY IDX_CLI_RELEASE_ASSET_RELEASE (RELEASE_ID_),
  CONSTRAINT FK_CLI_RELEASE_ASSET_RELEASE FOREIGN KEY (RELEASE_ID_) REFERENCES cli_release (ID_) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
