USE `cligrep`;

INSERT INTO cli_registry (
  SLUG_,
  DISPLAY_NAME_,
  SUMMARY_,
  TYPE_,
  TAGS_JSON_,
  HELP_TEXT_,
  VERSION_TEXT_,
  POPULARITY_,
  RUNTIME_IMAGE_,
  ENABLED_,
  EXAMPLE_LINE_,
  ENVIRONMENT_KIND_,
  SOURCE_TYPE_,
  AUTHOR_,
  GITHUB_URL_,
  GITEE_URL_,
  LICENSE_,
  CREATED_AT_,
  ORIGINAL_COMMAND_,
  EXECUTABLE_
) VALUES
  ('grep', 'grep', 'Search text with regular expressions inside the sandbox.', 'system', '["search","busybox","text"]', 'Search text with regular expressions inside the sandbox. Example: grep --help.', 'busybox-1.36.1', 100, 'busybox:1.36.1', 1, 'grep --help', 'SANDBOX', 'container_binary', 'BusyBox', 'https://github.com/mirror/busybox', '', 'GPL-2.0', '2025-12-10 10:00:00.000', 'grep', 1),
  ('find', 'find', 'Traverse directory trees and match files in the sandbox runtime.', 'system', '["search","filesystem","busybox"]', 'Traverse directory trees and match files in the sandbox runtime. Example: find --help.', 'busybox-1.36.1', 96, 'busybox:1.36.1', 1, 'find --help', 'SANDBOX', 'container_binary', 'BusyBox', 'https://github.com/mirror/busybox', '', 'GPL-2.0', '2025-12-18 10:00:00.000', 'find', 1),
  ('sed', 'sed', 'Stream editing for line-by-line text transformation.', 'system', '["transform","busybox","text"]', 'Stream editing for line-by-line text transformation. Example: sed --help.', 'busybox-1.36.1', 94, 'busybox:1.36.1', 1, 'sed --help', 'SANDBOX', 'container_binary', 'BusyBox', 'https://github.com/mirror/busybox', '', 'GPL-2.0', '2026-01-05 10:00:00.000', 'sed', 1),
  ('awk', 'awk', 'Pattern scanning and report generation for structured text.', 'system', '["report","busybox","text"]', 'Pattern scanning and report generation for structured text. Example: awk --help.', 'busybox-1.36.1', 92, 'busybox:1.36.1', 1, 'awk --help', 'SANDBOX', 'container_binary', 'BusyBox', 'https://github.com/mirror/busybox', '', 'GPL-2.0', '2026-01-14 10:00:00.000', 'awk', 1),
  ('ls', 'ls', 'List files and inspect directories within the isolated container.', 'system', '["list","filesystem","busybox"]', 'List files and inspect directories within the isolated container. Example: ls --help.', 'busybox-1.36.1', 88, 'busybox:1.36.1', 1, 'ls --help', 'SANDBOX', 'container_binary', 'BusyBox', 'https://github.com/mirror/busybox', '', 'GPL-2.0', '2026-02-01 10:00:00.000', 'ls', 1),
  ('sort', 'sort', 'Sort textual input with standard shell-friendly switches.', 'system', '["sort","busybox","text"]', 'Sort textual input with standard shell-friendly switches. Example: sort --help.', 'busybox-1.36.1', 86, 'busybox:1.36.1', 1, 'sort --help', 'SANDBOX', 'container_binary', 'BusyBox', 'https://github.com/mirror/busybox', '', 'GPL-2.0', '2026-02-12 10:00:00.000', 'sort', 1),
  ('rg', 'ripgrep', 'A Rust-native recursive search CLI with fast ignore handling.', 'native', '["search","native-rust","text"]', 'A Rust-native recursive search CLI with fast ignore handling. Indexed for documentation only on CLI Grep. Original command: rg. Example: rg TODO src.', 'docs-only', 99, 'text-only', 1, 'rg TODO src', 'TEXT', 'native_rust', 'BurntSushi', 'https://github.com/BurntSushi/ripgrep', '', 'MIT OR Unlicense', '2026-03-01 10:00:00.000', 'rg', 0),
  ('fd', 'fd', 'A user-friendly Rust-native alternative to find.', 'native', '["search","native-rust","filesystem"]', 'A user-friendly Rust-native alternative to find. Indexed for documentation only on CLI Grep. Original command: fd. Example: fd package json.', 'docs-only', 91, 'text-only', 1, 'fd package json', 'TEXT', 'native_rust', 'sharkdp', 'https://github.com/sharkdp/fd', '', 'MIT OR Apache-2.0', '2026-02-24 10:00:00.000', 'fd', 0),
  ('glow', 'glow', 'A native Go markdown reader for terminal-first documentation.', 'native', '["docs","native-go","markdown"]', 'A native Go markdown reader for terminal-first documentation. Indexed for documentation only on CLI Grep. Original command: glow. Example: glow README.md.', 'docs-only', 83, 'text-only', 1, 'glow README.md', 'TEXT', 'native_go', 'Charmbracelet', 'https://github.com/charmbracelet/glow', '', 'MIT', '2026-01-28 10:00:00.000', 'glow', 0),
  ('uv', 'uv', 'Rust-based Python tooling for environments and package management.', 'native', '["python","native-rust","package-manager"]', 'Rust-based Python tooling for environments and package management. Indexed for documentation only on CLI Grep. Original command: uv. Example: uv pip install rich.', 'docs-only', 97, 'text-only', 1, 'uv pip install rich', 'TEXT', 'native_rust', 'Astral', 'https://github.com/astral-sh/uv', '', 'MIT OR Apache-2.0', '2026-03-10 10:00:00.000', 'uv', 0),
  ('npm', 'npm', 'Node package manager help and usage reference.', 'text', '["node","package-manager","help-only"]', 'Node package manager help and usage reference. Indexed for documentation only on CLI Grep. Original command: npm. Example: npm install vite.', 'docs-only', 95, 'text-only', 1, 'npm install vite', 'TEXT', 'package_manager', 'npm', 'https://github.com/npm/cli', '', 'Artistic-2.0', '2026-02-20 10:00:00.000', 'npm', 0),
  ('apt', 'apt', 'APT package manager reference for Debian and Ubuntu systems.', 'text', '["linux","package-manager","help-only"]', 'APT package manager reference for Debian and Ubuntu systems. Indexed for documentation only on CLI Grep. Original command: apt. Example: apt install ripgrep.', 'docs-only', 89, 'text-only', 1, 'apt install ripgrep', 'TEXT', 'package_manager', 'Debian APT Team', '', '', 'GPL-2.0', '2026-01-22 10:00:00.000', 'apt', 0),
  ('mcp-inspect', 'mcp inspect', 'Inspect an MCP server manifest and bridge metadata through a CLI wrapper.', 'gateway', '["mcp","bridge","tooling"]', 'Inspect an MCP server manifest and bridge metadata through a CLI wrapper. Indexed for documentation only on CLI Grep. Original command: mcp-inspect. Example: mcp-inspect server.json.', 'docs-only', 79, 'text-only', 1, 'mcp-inspect server.json', 'TEXT', 'mcp_bridge', 'CLI Grep Labs', '', '', 'Apache-2.0', '2026-03-14 10:00:00.000', 'mcp-inspect', 0),
  ('yt-skim.py', 'yt-skim.py', 'A Python script CLI for skimming transcripts and producing notes.', 'gateway', '["python","script","notes"]', 'A Python script CLI for skimming transcripts and producing notes. Indexed for documentation only on CLI Grep. Original command: python yt_skim.py. Example: yt-skim.py https://youtu.be/demo.', 'docs-only', 76, 'text-only', 1, 'yt-skim.py https://youtu.be/demo', 'TEXT', 'python_script', 'CLI Grep Labs', '', '', 'MIT', '2026-03-06 10:00:00.000', 'python yt_skim.py', 0),
  ('dbx', 'dbx', 'A database CLI for humans and agents with explicit query, update, schema, and export workflows.', 'native', '["database","go","release-indexed"]', 'A database CLI for humans and agents with explicit query, update, schema, and export workflows. Indexed for documentation only on CLI Grep. Original command: dbx. Example: dbx version.', 'release-indexed', 90, 'text-only', 1, 'dbx version', 'TEXT', 'native_go', 'linlay', 'https://github.com/linlay/cli-dbx', '', 'MIT', '2026-03-25 10:00:00.000', 'dbx', 0),
  ('httpx', 'httpx', 'An HTTP CLI for stateful login flows, scripted requests, and response extraction.', 'native', '["http","go","release-indexed"]', 'An HTTP CLI for stateful login flows, scripted requests, and response extraction. Indexed for documentation only on CLI Grep. Original command: httpx. Example: httpx version.', 'release-indexed', 89, 'text-only', 1, 'httpx version', 'TEXT', 'native_go', 'linlay', 'https://github.com/linlay/cli-httpx', '', 'MIT', '2026-03-26 10:00:00.000', 'httpx', 0),
  ('himalaya', 'himalaya', 'A terminal-first email CLI with IMAP, SMTP, templates, and account-aware workflows.', 'native', '["email","rust","release-indexed"]', 'A terminal-first email CLI with IMAP, SMTP, templates, and account-aware workflows. Indexed for documentation only on CLI Grep. Original command: himalaya. Example: himalaya --version.', 'release-indexed', 87, 'text-only', 1, 'himalaya --version', 'TEXT', 'native_rust', 'pimalaya', 'https://github.com/pimalaya/himalaya', '', 'MIT', '2026-02-19 10:00:00.000', 'himalaya', 0),
  ('builtin-grep', 'builtin grep', 'The website-native registry search command.', 'builtin', '["builtin","search","core"]', 'Use grep <query> to search indexed CLIs.', 'cligrep builtin v2', 110, 'website', 1, 'grep rip', 'WEBSITE', 'website_builtin', 'CLI Grep', '', '', 'Proprietary', '2026-01-01 10:00:00.000', 'grep', 1),
  ('builtin-create', 'builtin create', 'Generate Python CLI scaffolds inside the website flow.', 'builtin', '["builtin","generator","python"]', 'Use create python \"your spec\".', 'cligrep builtin v2', 75, 'website', 1, 'create python \"make a todo cli\"', 'WEBSITE', 'website_builtin', 'CLI Grep', '', '', 'Proprietary', '2026-01-02 10:00:00.000', 'create python', 1),
  ('builtin-make', 'builtin make', 'Generate Dockerfile and sandbox recipe previews for CLIs.', 'builtin', '["builtin","docker","sandbox"]', 'Use make sandbox <cli> or make dockerfile <cli>.', 'cligrep builtin v2', 72, 'website', 1, 'make dockerfile grep', 'WEBSITE', 'website_builtin', 'CLI Grep', '', '', 'Proprietary', '2026-01-03 10:00:00.000', 'make', 1)
ON DUPLICATE KEY UPDATE
  DISPLAY_NAME_ = VALUES(DISPLAY_NAME_),
  SUMMARY_ = VALUES(SUMMARY_),
  TYPE_ = VALUES(TYPE_),
  TAGS_JSON_ = VALUES(TAGS_JSON_),
  HELP_TEXT_ = VALUES(HELP_TEXT_),
  VERSION_TEXT_ = VALUES(VERSION_TEXT_),
  POPULARITY_ = VALUES(POPULARITY_),
  RUNTIME_IMAGE_ = VALUES(RUNTIME_IMAGE_),
  ENABLED_ = VALUES(ENABLED_),
  EXAMPLE_LINE_ = VALUES(EXAMPLE_LINE_),
  ENVIRONMENT_KIND_ = VALUES(ENVIRONMENT_KIND_),
  SOURCE_TYPE_ = VALUES(SOURCE_TYPE_),
  AUTHOR_ = VALUES(AUTHOR_),
  GITHUB_URL_ = VALUES(GITHUB_URL_),
  GITEE_URL_ = VALUES(GITEE_URL_),
  LICENSE_ = VALUES(LICENSE_),
  CREATED_AT_ = VALUES(CREATED_AT_),
  ORIGINAL_COMMAND_ = VALUES(ORIGINAL_COMMAND_),
  EXECUTABLE_ = VALUES(EXECUTABLE_);
