USE `cligrep`;

INSERT INTO cli_registry (
  SLUG_,
  DISPLAY_NAME_,
  SUMMARY_,
  TYPE_,
  TAGS_JSON_,
  HELP_TEXT_,
  VERSION_TEXT_,
  POPULARITY_,
  RUNTIME_IMAGE_,
  ENABLED_,
  EXAMPLE_LINE_,
  ENVIRONMENT_KIND_,
  SOURCE_TYPE_,
  AUTHOR_,
  OFFICIAL_URL_,
  GITEE_URL_,
  LICENSE_,
  CREATED_AT_,
  ORIGINAL_COMMAND_,
  EXECUTABLE_
) VALUES
  ('grep', 'grep', 'Search text with regular expressions inside the sandbox.', 'system', '["search","busybox","text"]', 'Search text with regular expressions inside the sandbox. Example: grep --help.', 'busybox-1.36.1', 100, 'busybox:1.36.1', 1, 'grep --help', 'SANDBOX', 'container_binary', 'BusyBox', 'https://github.com/mirror/busybox', '', 'GPL-2.0', '2025-12-10 10:00:00.000', 'grep', 1),
  ('find', 'find', 'Traverse directory trees and match files in the sandbox runtime.', 'system', '["search","filesystem","busybox"]', 'Traverse directory trees and match files in the sandbox runtime. Example: find --help.', 'busybox-1.36.1', 96, 'busybox:1.36.1', 1, 'find --help', 'SANDBOX', 'container_binary', 'BusyBox', 'https://github.com/mirror/busybox', '', 'GPL-2.0', '2025-12-18 10:00:00.000', 'find', 1),
  ('sed', 'sed', 'Stream editing for line-by-line text transformation.', 'system', '["transform","busybox","text"]', 'Stream editing for line-by-line text transformation. Example: sed --help.', 'busybox-1.36.1', 94, 'busybox:1.36.1', 1, 'sed --help', 'SANDBOX', 'container_binary', 'BusyBox', 'https://github.com/mirror/busybox', '', 'GPL-2.0', '2026-01-05 10:00:00.000', 'sed', 1),
  ('awk', 'awk', 'Pattern scanning and report generation for structured text.', 'system', '["report","busybox","text"]', 'Pattern scanning and report generation for structured text. Example: awk --help.', 'busybox-1.36.1', 92, 'busybox:1.36.1', 1, 'awk --help', 'SANDBOX', 'container_binary', 'BusyBox', 'https://github.com/mirror/busybox', '', 'GPL-2.0', '2026-01-14 10:00:00.000', 'awk', 1),
  ('ls', 'ls', 'List files and inspect directories within the isolated container.', 'system', '["list","filesystem","busybox"]', 'List files and inspect directories within the isolated container. Example: ls --help.', 'busybox-1.36.1', 88, 'busybox:1.36.1', 1, 'ls --help', 'SANDBOX', 'container_binary', 'BusyBox', 'https://github.com/mirror/busybox', '', 'GPL-2.0', '2026-02-01 10:00:00.000', 'ls', 1),
  ('sort', 'sort', 'Sort textual input with standard shell-friendly switches.', 'system', '["sort","busybox","text"]', 'Sort textual input with standard shell-friendly switches. Example: sort --help.', 'busybox-1.36.1', 86, 'busybox:1.36.1', 1, 'sort --help', 'SANDBOX', 'container_binary', 'BusyBox', 'https://github.com/mirror/busybox', '', 'GPL-2.0', '2026-02-12 10:00:00.000', 'sort', 1),
  ('builtin-grep', 'builtin grep', 'The website-native registry search command.', 'builtin', '["builtin","search","core"]', 'Use grep <query> to search indexed CLIs.', 'cligrep builtin v2', 110, 'website', 1, 'grep rip', 'WEBSITE', 'website_builtin', 'CLI Grep', '', '', 'Proprietary', '2026-01-01 10:00:00.000', 'grep', 1),
  ('builtin-create', 'builtin create', 'Generate Python CLI scaffolds inside the website flow.', 'builtin', '["builtin","generator","python"]', 'Use create python \"your spec\".', 'cligrep builtin v2', 75, 'website', 1, 'create python \"make a todo cli\"', 'WEBSITE', 'website_builtin', 'CLI Grep', '', '', 'Proprietary', '2026-01-02 10:00:00.000', 'create python', 1),
  ('builtin-make', 'builtin make', 'Generate Dockerfile and sandbox recipe previews for CLIs.', 'builtin', '["builtin","docker","sandbox"]', 'Use make sandbox <cli> or make dockerfile <cli>.', 'cligrep builtin v2', 72, 'website', 1, 'make dockerfile grep', 'WEBSITE', 'website_builtin', 'CLI Grep', '', '', 'Proprietary', '2026-01-03 10:00:00.000', 'make', 1)
ON DUPLICATE KEY UPDATE
  DISPLAY_NAME_ = VALUES(DISPLAY_NAME_),
  SUMMARY_ = VALUES(SUMMARY_),
  TYPE_ = VALUES(TYPE_),
  TAGS_JSON_ = VALUES(TAGS_JSON_),
  HELP_TEXT_ = VALUES(HELP_TEXT_),
  VERSION_TEXT_ = VALUES(VERSION_TEXT_),
  POPULARITY_ = VALUES(POPULARITY_),
  RUNTIME_IMAGE_ = VALUES(RUNTIME_IMAGE_),
  ENABLED_ = VALUES(ENABLED_),
  EXAMPLE_LINE_ = VALUES(EXAMPLE_LINE_),
  ENVIRONMENT_KIND_ = VALUES(ENVIRONMENT_KIND_),
  SOURCE_TYPE_ = VALUES(SOURCE_TYPE_),
  AUTHOR_ = VALUES(AUTHOR_),
  OFFICIAL_URL_ = VALUES(OFFICIAL_URL_),
  GITEE_URL_ = VALUES(GITEE_URL_),
  LICENSE_ = VALUES(LICENSE_),
  CREATED_AT_ = VALUES(CREATED_AT_),
  ORIGINAL_COMMAND_ = VALUES(ORIGINAL_COMMAND_),
  EXECUTABLE_ = VALUES(EXECUTABLE_);
